version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database-seeds:/docker-entrypoint-initdb.d:ro
    ports:
      - '27018:27017'
    networks:
      - private

  welcome_service:
    image: 'ambystomatidae/welcome-service:latest'
    container_name: 'welcome_service'
    env_file: ./welcome-service/.env.example
    networks:
      - private
    depends_on:
      - database

  crosswalks_location_service:
    build:
      context: ./crosswalks-location-service/
      dockerfile: Dockerfile
    container_name: 'crosswalks_location_service'
    env_file: ./crosswalks-location-service/.env.example
    ports:
      - '3001:3000'
    networks:
      - private
    restart: on-failure
    depends_on:
      - database
      - rabbit


  spws_web_app:
    image: 'ambystomatidae/spws-web-app:latest'
    container_name: 'spws_web_app'
    ports:
      - '8080:8080'
    networks:
      - public

  spws:
    build:
      context: ./spws
      dockerfile: Dockerfile
    container_name: 'spws'
    env_file: ./spws/.env.example
    ports:
      - '3000:3000'
    networks:
      - private
      - public
    depends_on:
      - database
      - welcome_service
      - crosswalks_location_service

  rabbit:
    build:
      context: ./
      dockerfile: rabbit.Dockerfile
    container_name: 'rabbit'
    ports:
      - '5672:5672' #amqp
      - '15672:15672' #http
      - '15674:15674' #web-stomp
    networks:
      - private
      - public
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  crosswalks_current_status_service:
    build:
      context: './crosswalks-current-status-service/'
      dockerfile: Dockerfile
    container_name: 'crosswalks_current_status_service'
    env_file: './crosswalks-current-status-service/.env.example'
    restart: on-failure
    networks:
      - private
    depends_on:
      - database
      - rabbit

  traffic_light_simulator:
    build:
      context: ./traffic-light-simulator
      dockerfile: Dockerfile
    container_name: 'traffic_light_simulator'
    env_file: ./traffic-light-simulator/.env.example
    restart: on-failure
    depends_on:
      - crosswalks_location_service
      - rabbit
    networks:
      - private

  crosswalks_logger_service:
    build:
      context: ./crosswalks-logger-service
      dockerfile: Dockerfile
    container_name: 'crosswalks_logger_service'
    env_file: ./crosswalks-logger-service/.env.example
    restart: on-failure
    depends_on:
      - crosswalks_location_service
      - rabbit
      - database
    networks:
      - private

networks:
  private:
    driver: bridge
  public:
    driver: bridge
