version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database-seeds:/docker-entrypoint-initdb.d:ro
    networks:
      - private

  welcome_service:
    image: 'ambystomatidae/welcome-service:latest'
    container_name: 'welcome_service'
    env_file: ./welcome-service/.env.example
    networks:
      - private
    depends_on: 
      - database

  crosswalks_location_service:
    image: 'ambystomatidae/crosswalks-location-service:latest'
    container_name: 'crosswalks_location_service'
    env_file: ./crosswalks-location-service/.env.example
    ports:
      - '3001:3000'
    networks:
      - private
    depends_on:
      - database


  spws_web_app:
    image: 'ambystomatidae/spws-web-app:latest'
    container_name: 'spws_web_app'
    ports:
      - '8080:8080'
    networks:
      - public

  spws:
    image: 'ambystomatidae/spws:latest'
    container_name: 'spws'
    env_file: ./spws/.env.example
    ports:
      - '3000:3000'
    networks:
      - private
      - public
    depends_on: 
      - database
      - welcome_service
      - crosswalks_location_service

  rabbit:
    image: 'rabbitmq:3.8.3-management-alpine'
    ports:
      - '5672:5672' #amqp
      - '15672:15672' #http
    networks:
      - private
      - public

networks:
  private:
    driver: bridge
  public:
    driver: bridge

    