version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'

  rabbit:
    image: 'rabbitmq:3.8.3-management-alpine'
    container_name: 'rabbit'
    ports:
      - '5672:5672' #amqp
      - '15672:15672' #http
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

    