version: '3.1'
services:
  database:
    image: 'mongo'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports: 
      - '27017-27019:27017-27019'
  nearby_crosswalks_service:
    container_name: nearby_crosswalks_service
    restart: always
    build: .
    ports:
      - '5000:3000'
    links: 
      - database
