steps:
  - name: 'node:10-alpine'
    id: Install
    entrypoint: npm
    args: [ 'install' ]
    dir: 'welcome-service'
    timeout: '60s'

  - name: 'node:10-alpine'
    id: Test
    entrypoint: npm
    args: [ 'test' ]
    dir: 'welcome-service'
    timeout: '60s'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args: [ 'app', 'deploy']
    dir: 'welcome-service'
    timeout: '600s'