FROM node:14.2.0-alpine3.10

# Set env as dev
ENV NODE_ENV dev

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

CMD [ "npm", "test", "tests/test.js", "--exit"]
