name: dev-vehicle-app

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'vehicle-app/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './vehicle-app'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check node version in .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test